services:
  postgres:
    image: 'postgres:latest'
    container_name: 'postgres_db_handcrafted'
    restart: 'always'
    environment:
      - 'POSTGRES_DB=handcrafted_data'
      - 'POSTGRES_USER=postgres_user'
      - 'POSTGRES_PASSWORD=postgres_pass'
    ports:
      - '5432'

networks:
  default:
    name: 'handcrafted_network'