spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/handcrafted_data'
    username: 'postgres_user'
    password: 'postgres_pass'
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
  docker:
    compose:
      lifecycle-management: start_only