spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/currency_data'
    username: 'postgres_user'
    password: 'postgres_pass'
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
  jpa:
    database-platform: 'org.hibernate.dialect.PostgreSQLDialect'
  docker:
    compose:
      lifecycle-management: start_only