CREATE SCHEMA IF NOT EXISTS HANDCRAFTED_SCHEMA;

CREATE SEQUENCE IF NOT EXISTS HANDCRAFTED_SCHEMA.USER_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE IF NOT EXISTS HANDCRAFTED_SCHEMA.USER
(
    ID BIGINT DEFAULT nextval('HANDCRAFTED_SCHEMA.USER_SEQ'),
    USER_NAME VARCHAR(20) NOT NULL,
    NAME VARCHAR(20) NOT NULL,
    SURNAME VARCHAR(20) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ACTIVE BOOLEAN NOT NULL,
    USER_PHONE BIGINT,

    CONSTRAINT PK_USER PRIMARY KEY (ID),
    CONSTRAINT UQ_USER_USER_NAME UNIQUE (USER_NAME)
);

CREATE TABLE IF NOT EXISTS HANDCRAFTED_SCHEMA.USER_ROLE
(
    USER_ID BIGINT NOT NULL,
    ROLES VARCHAR(5) NOT NULL,

    CONSTRAINT PK_USER_ROLE PRIMARY KEY (USER_ID, ROLES),
    CONSTRAINT FK_USER_ROLE_USER_ID FOREIGN KEY (USER_ID) REFERENCES HANDCRAFTED_SCHEMA.USER (ID) ON DELETE CASCADE
);

CREATE SEQUENCE IF NOT EXISTS HANDCRAFTED_SCHEMA.CATEGORY_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE IF NOT EXISTS HANDCRAFTED_SCHEMA.CATEGORY
(
    ID BIGINT DEFAULT nextval('HANDCRAFTED_SCHEMA.CATEGORY_SEQ'),
    NAME VARCHAR(30) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,

    CONSTRAINT PK_CATEGORY PRIMARY KEY (ID),
    CONSTRAINT UQ_CATEGORY_NAME UNIQUE (NAME)
);

CREATE SEQUENCE IF NOT EXISTS HANDCRAFTED_SCHEMA.COLOR_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE IF NOT EXISTS HANDCRAFTED_SCHEMA.COLOR
(
    ID BIGINT DEFAULT nextval('HANDCRAFTED_SCHEMA.COLOR_SEQ'),
    NAME VARCHAR(20) NOT NULL,

    CONSTRAINT PK_COLOR PRIMARY KEY (ID),
    CONSTRAINT UQ_COLOR_NAME UNIQUE (NAME)
);

CREATE SEQUENCE IF NOT EXISTS HANDCRAFTED_SCHEMA.PRODUCT_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE IF NOT EXISTS HANDCRAFTED_SCHEMA.PRODUCT
(
    ID BIGINT DEFAULT nextval('HANDCRAFTED_SCHEMA.PRODUCT_SEQ'),
    NAME VARCHAR(25) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    KEY_WORDS VARCHAR(255) NOT NULL,
    PRICE NUMERIC NOT NULL,
    WITH_DISCOUNT BOOLEAN NOT NULL,
    DISCOUNTED_PRICE NUMERIC NULL,
    IN_STOCK BOOLEAN NOT NULL,
    QUANTITY INT NOT NULL,
    CREATION_DATE TIMESTAMP NOT NULL,
    CATEGORY_ID BIGINT NULL,
    DELETED BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT PK_PRODUCT PRIMARY KEY (ID),
    CONSTRAINT FK_PRODUCT_CATEGORY_ID FOREIGN KEY (CATEGORY_ID) REFERENCES HANDCRAFTED_SCHEMA.CATEGORY (ID)
);

CREATE SEQUENCE IF NOT EXISTS HANDCRAFTED_SCHEMA.COLOR_IN_PRODUCT_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE IF NOT EXISTS HANDCRAFTED_SCHEMA.COLOR_IN_PRODUCT
(
    ID BIGINT DEFAULT nextval('HANDCRAFTED_SCHEMA.COLOR_IN_PRODUCT_SEQ'),
    COLOR_ID BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,

    CONSTRAINT PK_COLOR_IN_PRODUCT PRIMARY KEY (ID),
    CONSTRAINT FK_COLOR_IN_PRODUCT_COLOR_ID FOREIGN KEY (COLOR_ID) REFERENCES HANDCRAFTED_SCHEMA.COLOR (ID) ON DELETE CASCADE,
    CONSTRAINT FK_COLOR_IN_PRODUCT_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES HANDCRAFTED_SCHEMA.PRODUCT (ID) ON DELETE CASCADE
);

CREATE SEQUENCE IF NOT EXISTS HANDCRAFTED_SCHEMA.PHOTO_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE IF NOT EXISTS HANDCRAFTED_SCHEMA.PHOTO
(
    ID BIGINT DEFAULT nextval('HANDCRAFTED_SCHEMA.PHOTO_SEQ'),
    NAME VARCHAR(255) NOT NULL,
    DATA BYTEA NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,

    CONSTRAINT PK_PHOTO PRIMARY KEY (ID),
    CONSTRAINT FK_PHOTO_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES HANDCRAFTED_SCHEMA.PRODUCT (ID) ON DELETE CASCADE
);

CREATE SEQUENCE IF NOT EXISTS HANDCRAFTED_SCHEMA.FAVORITE_PRODUCT_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE IF NOT EXISTS HANDCRAFTED_SCHEMA.FAVORITE_PRODUCT
(
    ID BIGINT DEFAULT nextval('HANDCRAFTED_SCHEMA.FAVORITE_PRODUCT_SEQ'),
    USER_ID BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,

    CONSTRAINT PK_FAVORITE_PRODUCT PRIMARY KEY (ID),
    CONSTRAINT FK_FAVORITE_PRODUCT_USER_ID FOREIGN KEY (USER_ID) REFERENCES HANDCRAFTED_SCHEMA.USER (ID) ON DELETE CASCADE,
    CONSTRAINT FK_FAVORITE_PRODUCT_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES HANDCRAFTED_SCHEMA.PRODUCT (ID) ON DELETE CASCADE
);

CREATE SEQUENCE IF NOT EXISTS HANDCRAFTED_SCHEMA.PRODUCT_IN_CART_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE IF NOT EXISTS HANDCRAFTED_SCHEMA.PRODUCT_IN_CART
(
    ID BIGINT DEFAULT nextval('HANDCRAFTED_SCHEMA.PRODUCT_IN_CART_SEQ'),
    USER_ID BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    QUANTITY BIGINT NOT NULL,

    CONSTRAINT PK_PRODUCT_IN_CART PRIMARY KEY (ID),
    CONSTRAINT FK_PRODUCT_IN_CART_USER_ID FOREIGN KEY (USER_ID) REFERENCES HANDCRAFTED_SCHEMA.USER (ID) ON DELETE CASCADE,
    CONSTRAINT FK_PRODUCT_IN_CART_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES HANDCRAFTED_SCHEMA.PRODUCT (ID) ON DELETE CASCADE
    );

CREATE SEQUENCE IF NOT EXISTS HANDCRAFTED_SCHEMA.ORDER_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE IF NOT EXISTS HANDCRAFTED_SCHEMA.ORDER
(
    ID BIGINT DEFAULT nextval('HANDCRAFTED_SCHEMA.ORDER_SEQ'),
    USER_ID BIGINT NOT NULL,
    USER_PHONE BIGINT NOT NULL,
    PRICE NUMERIC NOT NULL,
    FORMATION_DATE TIMESTAMP NOT NULL,
    STATUS VARCHAR(22) NOT NULL,
    TYPE_OF_RECEIPT VARCHAR(27) NOT NULL,
    RECEIPT_DATE TIMESTAMP NULL,
    DELIVERY_ADDRESS_REGION VARCHAR(255) NULL,
    DELIVERY_ADDRESS_CITY VARCHAR(255) NULL,
    DELIVERY_ADDRESS_POST_ADDRESS VARCHAR(255) NULL,
    INVOICE_NUMBER BIGINT NULL,

    CONSTRAINT PK_ORDER PRIMARY KEY (ID),
    CONSTRAINT FK_ORDER_USER_ID FOREIGN KEY (USER_ID) REFERENCES HANDCRAFTED_SCHEMA.USER (ID) ON DELETE NO ACTION
);

CREATE SEQUENCE IF NOT EXISTS HANDCRAFTED_SCHEMA.PRODUCT_IN_ORDER_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE IF NOT EXISTS HANDCRAFTED_SCHEMA.PRODUCT_IN_ORDER
(
    ID BIGINT DEFAULT nextval('HANDCRAFTED_SCHEMA.PRODUCT_IN_ORDER_SEQ'),
    ORDER_ID BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    PRODUCT_COST NUMERIC NOT NULL,
    QUANTITY BIGINT NOT NULL,

    CONSTRAINT PK_PRODUCT_IN_ORDER PRIMARY KEY (ID),
    CONSTRAINT FK_PRODUCT_IN_ORDER_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES HANDCRAFTED_SCHEMA.PRODUCT (ID) ON DELETE CASCADE,
    CONSTRAINT FK_PRODUCT_IN_ORDER_ORDER_ID FOREIGN KEY (ORDER_ID) REFERENCES HANDCRAFTED_SCHEMA.ORDER (ID) ON DELETE CASCADE
);