CREATE SCHEMA IF NOT EXISTS HANDCRAFTED_SCHEMA;

CREATE SEQUENCE IF NOT EXISTS HANDCRAFTED_SCHEMA.USER_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE IF NOT EXISTS HANDCRAFTED_SCHEMA.USER
(
    ID BIGINT DEFAULT nextval('HANDCRAFTED_SCHEMA.USER_SEQ'),
    USER_NAME VARCHAR(20) NOT NULL,
    NAME VARCHAR(20) NOT NULL,
    SURNAME VARCHAR(20) NOT NULL,
    PASSWORD VARCHAR(12) NOT NULL,
    USER_PHONE BIGINT,

    CONSTRAINT PK_USER PRIMARY KEY (ID),
    CONSTRAINT UQ_USER_USER_NAME UNIQUE (USER_NAME)
);

CREATE SEQUENCE IF NOT EXISTS HANDCRAFTED_SCHEMA.CATEGORY_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE IF NOT EXISTS HANDCRAFTED_SCHEMA.CATEGORY
(
    ID BIGINT DEFAULT nextval('HANDCRAFTED_SCHEMA.CATEGORY_SEQ'),
    NAME VARCHAR(30) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,

    CONSTRAINT PK_CATEGORY PRIMARY KEY (ID),
    CONSTRAINT UQ_CATEGORY_NAME UNIQUE (NAME)
);

CREATE SEQUENCE IF NOT EXISTS HANDCRAFTED_SCHEMA.COLOR_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE IF NOT EXISTS HANDCRAFTED_SCHEMA.COLOR
(
    ID BIGINT DEFAULT nextval('HANDCRAFTED_SCHEMA.COLOR_SEQ'),
    NAME VARCHAR(20) NOT NULL,

    CONSTRAINT PK_COLOR PRIMARY KEY (ID),
    CONSTRAINT UQ_COLOR_NAME UNIQUE (NAME)
);

CREATE SEQUENCE IF NOT EXISTS HANDCRAFTED_SCHEMA.PRODUCT_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE IF NOT EXISTS HANDCRAFTED_SCHEMA.PRODUCT
(
    ID BIGINT DEFAULT nextval('HANDCRAFTED_SCHEMA.PRODUCT_SEQ'),
    NAME VARCHAR(20) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    KEY_WORDS VARCHAR(255) NOT NULL,
    PRICE NUMERIC NOT NULL,
    WITH_DISCOUNT BOOLEAN NOT NULL,
    DISCOUNTED_PRICE NUMERIC NULL,
    IN_STOCK BOOLEAN NOT NULL,
    QUANTITY INT NOT NULL,
    CREATION_DATE DATE NOT NULL,
    CATEGORY_ID BIGINT NULL,

    CONSTRAINT PK_PRODUCT PRIMARY KEY (ID),
    CONSTRAINT FK_PRODUCT_CATEGORY_ID FOREIGN KEY (CATEGORY_ID) REFERENCES HANDCRAFTED_SCHEMA.CATEGORY (ID)
);

CREATE TABLE IF NOT EXISTS HANDCRAFTED_SCHEMA.COLORS_IN_PRODUCT
(
    COLOR_ID BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,

    CONSTRAINT PK_COLORS_IN_PRODUCT PRIMARY KEY (COLOR_ID, PRODUCT_ID),
    CONSTRAINT FK_COLORS_IN_PRODUCT_COLOR_ID FOREIGN KEY (COLOR_ID) REFERENCES HANDCRAFTED_SCHEMA.COLOR (ID),
    CONSTRAINT FK_COLORS_IN_PRODUCT_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES HANDCRAFTED_SCHEMA.PRODUCT (ID)
);

CREATE SEQUENCE IF NOT EXISTS HANDCRAFTED_SCHEMA.PHOTO_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE IF NOT EXISTS HANDCRAFTED_SCHEMA.PHOTO
(
    ID BIGINT DEFAULT nextval('HANDCRAFTED_SCHEMA.PHOTO_SEQ'),
    NAME VARCHAR(255) NOT NULL,
    DATA BYTEA NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,

    CONSTRAINT PK_PHOTO PRIMARY KEY (ID),
    CONSTRAINT FK_PHOTO_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES HANDCRAFTED_SCHEMA.PRODUCT (ID)
);

CREATE TABLE IF NOT EXISTS HANDCRAFTED_SCHEMA.FAVORITE_PRODUCTS
(
    USER_ID BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,

    CONSTRAINT PK_FAVORITE_PRODUCTS PRIMARY KEY (USER_ID, PRODUCT_ID),
    CONSTRAINT FK_FAVORITE_PRODUCTS_USER_ID FOREIGN KEY (USER_ID) REFERENCES HANDCRAFTED_SCHEMA.USER (ID),
    CONSTRAINT FK_FAVORITE_PRODUCTS_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES HANDCRAFTED_SCHEMA.PRODUCT (ID)
);

CREATE TABLE IF NOT EXISTS HANDCRAFTED_SCHEMA.PRODUCTS_IN_CART
(
    USER_ID BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,

    CONSTRAINT PK_PRODUCTS_IN_CART PRIMARY KEY (USER_ID, PRODUCT_ID),
    CONSTRAINT FK_PRODUCTS_IN_CART_USER_ID FOREIGN KEY (USER_ID) REFERENCES HANDCRAFTED_SCHEMA.USER (ID),
    CONSTRAINT FK_PRODUCTS_IN_CART_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES HANDCRAFTED_SCHEMA.PRODUCT (ID)
    );

CREATE SEQUENCE IF NOT EXISTS HANDCRAFTED_SCHEMA.ORDER_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE IF NOT EXISTS HANDCRAFTED_SCHEMA.ORDER
(
    ID BIGINT DEFAULT nextval('HANDCRAFTED_SCHEMA.ORDER_SEQ'),
    USER_ID BIGINT NOT NULL,
    USER_PHONE BIGINT NOT NULL,
    PRICE NUMERIC NOT NULL,
    FORMATION_DATE DATE NOT NULL,
    STATUS VARCHAR(22) NOT NULL,
    TYPE_OF_RECEIPT VARCHAR(27) NOT NULL,
    RECEIPT_DATE DATE NULL,
    DELIVERY_ADDRESS VARCHAR(255) NULL,
    INVOICE_NUMBER BIGINT NULL,

    CONSTRAINT PK_ORDER PRIMARY KEY (ID),
    CONSTRAINT FK_ORDER_USER_ID FOREIGN KEY (USER_ID) REFERENCES HANDCRAFTED_SCHEMA.USER (ID)
);

CREATE TABLE IF NOT EXISTS HANDCRAFTED_SCHEMA.PRODUCTS_IN_ORDER
(
    PRODUCT_ID BIGINT NOT NULL,
    ORDER_ID BIGINT NOT NULL,
    QUANTITY BIGINT NOT NULL,

    CONSTRAINT PK_PRODUCTS_IN_ORDER PRIMARY KEY (PRODUCT_ID, ORDER_ID),
    CONSTRAINT FK_PRODUCTS_IN_ORDER_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES HANDCRAFTED_SCHEMA.PRODUCT (ID),
    CONSTRAINT FK_PRODUCTS_IN_ORDER_ORDER_ID FOREIGN KEY (ORDER_ID) REFERENCES HANDCRAFTED_SCHEMA.ORDER (ID)
);