CREATE SCHEMA IF NOT EXISTS HANDCRAFTED_SCHEMA;

CREATE SEQUENCE IF NOT EXISTS HANDCRAFTED_SCHEMA.USER_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE IF NOT EXISTS HANDCRAFTED_SCHEMA.USER
(
    ID BIGINT DEFAULT nextval('HANDCRAFTED_SCHEMA.USER_SEQ'),
    USER_NAME VARCHAR(20) NOT NULL,
    NAME VARCHAR(20) NOT NULL,
    SURNAME VARCHAR(20) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ACTIVE BOOLEAN NOT NULL,
    USER_PHONE BIGINT,

    CONSTRAINT PK_USER PRIMARY KEY (ID),
    CONSTRAINT UQ_USER_USER_NAME UNIQUE (USER_NAME)
    );

CREATE TABLE IF NOT EXISTS HANDCRAFTED_SCHEMA.USER_ROLE
(
    USER_ID BIGINT NOT NULL,
    ROLES VARCHAR(5) NOT NULL,

    CONSTRAINT PK_USER_ROLE PRIMARY KEY (USER_ID, ROLES),
    CONSTRAINT FK_USER_ROLE_USER_ID FOREIGN KEY (USER_ID) REFERENCES HANDCRAFTED_SCHEMA.USER (ID) ON DELETE CASCADE
    );

CREATE SEQUENCE IF NOT EXISTS HANDCRAFTED_SCHEMA.CATEGORY_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE IF NOT EXISTS HANDCRAFTED_SCHEMA.CATEGORY
(
    ID BIGINT DEFAULT nextval('HANDCRAFTED_SCHEMA.CATEGORY_SEQ'),
    NAME VARCHAR(30) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,

    CONSTRAINT PK_CATEGORY PRIMARY KEY (ID),
    CONSTRAINT UQ_CATEGORY_NAME UNIQUE (NAME)
    );

INSERT INTO HANDCRAFTED_SCHEMA.CATEGORY (NAME, DESCRIPTION)
VALUES
    ('Інше', 'Товари без категорії');

CREATE SEQUENCE IF NOT EXISTS HANDCRAFTED_SCHEMA.COLOR_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE IF NOT EXISTS HANDCRAFTED_SCHEMA.COLOR
(
    ID BIGINT DEFAULT nextval('HANDCRAFTED_SCHEMA.COLOR_SEQ'),
    NAME VARCHAR(20) NOT NULL,

    CONSTRAINT PK_COLOR PRIMARY KEY (ID),
    CONSTRAINT UQ_COLOR_NAME UNIQUE (NAME)
    );

CREATE SEQUENCE IF NOT EXISTS HANDCRAFTED_SCHEMA.PRODUCT_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE IF NOT EXISTS HANDCRAFTED_SCHEMA.PRODUCT
(
    ID BIGINT DEFAULT nextval('HANDCRAFTED_SCHEMA.PRODUCT_SEQ'),
    NAME VARCHAR(25) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    KEY_WORDS VARCHAR(255) NOT NULL,
    PRICE NUMERIC NOT NULL,
    WITH_DISCOUNT BOOLEAN NOT NULL,
    DISCOUNTED_PRICE NUMERIC NULL,
    IN_STOCK BOOLEAN NOT NULL,
    QUANTITY INT NOT NULL,
    CAN_ADD_TO_GIFT_SET BOOLEAN NOT NULL,
    MAX_QUANTITY_IN_GIFT_SET INT NOT NULL,
    CREATION_DATE TIMESTAMP NOT NULL,
    CATEGORY_ID BIGINT NOT NULL,
    DELETED BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT PK_PRODUCT PRIMARY KEY (ID),
    CONSTRAINT FK_PRODUCT_CATEGORY_ID FOREIGN KEY (CATEGORY_ID) REFERENCES HANDCRAFTED_SCHEMA.CATEGORY (ID),
    CONSTRAINT CK_PRODUCT_QUANTITY CHECK ( QUANTITY >= 0 )
    );

CREATE SEQUENCE IF NOT EXISTS HANDCRAFTED_SCHEMA.PRODUCT_PHOTO_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE IF NOT EXISTS HANDCRAFTED_SCHEMA.PRODUCT_PHOTO
(
    ID BIGINT DEFAULT nextval('HANDCRAFTED_SCHEMA.PRODUCT_PHOTO_SEQ'),
    PRODUCT_ID BIGINT NOT NULL,
    PHOTO TEXT NOT NULL,
    INDEX INT,

    CONSTRAINT PK_PHOTO_OF_PRODUCT PRIMARY KEY (ID),
    CONSTRAINT FK_PHOTO_OF_PRODUCT_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES HANDCRAFTED_SCHEMA.PRODUCT (ID) ON DELETE CASCADE
    );

CREATE TABLE IF NOT EXISTS HANDCRAFTED_SCHEMA.PRODUCT_COLOR
(
    PRODUCT_ID BIGINT NOT NULL,
    COLOR_ID BIGINT NOT NULL,

    CONSTRAINT PK_COLOR_IN_PRODUCT PRIMARY KEY (PRODUCT_ID, COLOR_ID),
    CONSTRAINT FK_COLOR_IN_PRODUCT_COLOR_ID FOREIGN KEY (COLOR_ID) REFERENCES HANDCRAFTED_SCHEMA.COLOR (ID) ON DELETE CASCADE,
    CONSTRAINT FK_COLOR_IN_PRODUCT_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES HANDCRAFTED_SCHEMA.PRODUCT (ID) ON DELETE CASCADE
    );

CREATE SEQUENCE IF NOT EXISTS HANDCRAFTED_SCHEMA.FAVORITE_PRODUCT_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE IF NOT EXISTS HANDCRAFTED_SCHEMA.FAVORITE_PRODUCT
(
    ID BIGINT DEFAULT nextval('HANDCRAFTED_SCHEMA.FAVORITE_PRODUCT_SEQ'),
    USER_ID BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,

    CONSTRAINT PK_FAVORITE_PRODUCT PRIMARY KEY (ID),
    CONSTRAINT FK_FAVORITE_PRODUCT_USER_ID FOREIGN KEY (USER_ID) REFERENCES HANDCRAFTED_SCHEMA.USER (ID) ON DELETE CASCADE,
    CONSTRAINT FK_FAVORITE_PRODUCT_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES HANDCRAFTED_SCHEMA.PRODUCT (ID) ON DELETE CASCADE
    );

CREATE SEQUENCE IF NOT EXISTS HANDCRAFTED_SCHEMA.GIFT_SET_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE IF NOT EXISTS HANDCRAFTED_SCHEMA.GIFT_SET
(
    ID BIGINT DEFAULT nextval('HANDCRAFTED_SCHEMA.GIFT_SET_SEQ'),
    USER_ID BIGINT NOT NULL,
    FORMATION_DATE TIMESTAMP NOT NULL,
    PACKAGING_WISHES VARCHAR(255),
    PRICE NUMERIC NOT NULL,

    CONSTRAINT PK_GIFT_SET PRIMARY KEY (ID),
    CONSTRAINT FK_GIFT_SET_USER_ID FOREIGN KEY (USER_ID) REFERENCES HANDCRAFTED_SCHEMA.USER (ID) ON DELETE CASCADE
);

CREATE SEQUENCE IF NOT EXISTS HANDCRAFTED_SCHEMA.GIFT_SET_ITEM_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE IF NOT EXISTS HANDCRAFTED_SCHEMA.GIFT_SET_ITEM
(
    ID BIGINT DEFAULT nextval('HANDCRAFTED_SCHEMA.GIFT_SET_ITEM_SEQ'),
    GIFT_SET_ID BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    QUANTITY BIGINT NOT NULL,
    PRODUCT_COST NUMERIC NOT NULL,

    CONSTRAINT PK_GIFT_SET_ITEM PRIMARY KEY (ID),
    CONSTRAINT FK_GIFT_SET_ITEM_GIFT_SET_ID FOREIGN KEY (GIFT_SET_ID) REFERENCES HANDCRAFTED_SCHEMA.GIFT_SET (ID) ON DELETE CASCADE,
    CONSTRAINT FK_GIFT_SET_ITEM_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES HANDCRAFTED_SCHEMA.PRODUCT (ID) ON DELETE CASCADE,
    CONSTRAINT CK_GIFT_SET_ITEM_QUANTITY CHECK ( QUANTITY > 0 )
);

CREATE SEQUENCE IF NOT EXISTS HANDCRAFTED_SCHEMA.CART_ITEM_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE IF NOT EXISTS HANDCRAFTED_SCHEMA.CART_ITEM
(
    ID BIGINT DEFAULT nextval('HANDCRAFTED_SCHEMA.CART_ITEM_SEQ'),
    USER_ID BIGINT NOT NULL,
    PRODUCT_ID BIGINT,
    GIFT_SET_ID BIGINT,
    QUANTITY BIGINT NOT NULL,

    CONSTRAINT PK_CART_ITEM PRIMARY KEY (ID),
    CONSTRAINT FK_CART_ITEM_USER_ID FOREIGN KEY (USER_ID) REFERENCES HANDCRAFTED_SCHEMA.USER (ID) ON DELETE CASCADE,
    CONSTRAINT FK_CART_ITEM_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES HANDCRAFTED_SCHEMA.PRODUCT (ID) ON DELETE CASCADE,
    CONSTRAINT FK_CART_ITEM_GIFT_SET_ID FOREIGN KEY (GIFT_SET_ID) REFERENCES HANDCRAFTED_SCHEMA.GIFT_SET (ID) ON DELETE CASCADE,
    CONSTRAINT CK_CART_ITEM_QUANTITY CHECK ( QUANTITY > 0 ),
    CONSTRAINT CK_CART_ITEM_PRODUCT_OR_GIFT_SET CHECK (
        (PRODUCT_ID IS NOT NULL AND GIFT_SET_ID IS NULL) OR
        (PRODUCT_ID IS NULL AND GIFT_SET_ID IS NOT NULL)
        )
    );

CREATE SEQUENCE IF NOT EXISTS HANDCRAFTED_SCHEMA.ORDER_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE IF NOT EXISTS HANDCRAFTED_SCHEMA.ORDER
(
    ID BIGINT DEFAULT nextval('HANDCRAFTED_SCHEMA.ORDER_SEQ'),
    USER_ID BIGINT NOT NULL,
    USER_PHONE BIGINT NOT NULL,
    PRICE NUMERIC NOT NULL,
    FORMATION_DATE TIMESTAMP NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    TYPE_OF_RECEIPT VARCHAR(29) NOT NULL,
    RECEIPT_DATE TIMESTAMP NULL,
    DELIVERY_ADDRESS_REGION VARCHAR(255) NULL,
    DELIVERY_ADDRESS_CITY VARCHAR(255) NULL,
    DELIVERY_ADDRESS_POST_ADDRESS VARCHAR(255) NULL,
    INVOICE_NUMBER BIGINT NULL,
    ORDER_COMMENTS VARCHAR(255),

    CONSTRAINT PK_ORDER PRIMARY KEY (ID),
    CONSTRAINT FK_ORDER_USER_ID FOREIGN KEY (USER_ID) REFERENCES HANDCRAFTED_SCHEMA.USER (ID) ON DELETE NO ACTION
    );

CREATE SEQUENCE IF NOT EXISTS HANDCRAFTED_SCHEMA.ORDER_ITEM_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE IF NOT EXISTS HANDCRAFTED_SCHEMA.ORDER_ITEM
(
    ID BIGINT DEFAULT nextval('HANDCRAFTED_SCHEMA.ORDER_ITEM_SEQ'),
    ORDER_ID BIGINT NOT NULL,
    PRODUCT_ID BIGINT,
    GIFT_SET_ID BIGINT,
    ITEM_COST NUMERIC NOT NULL,
    QUANTITY BIGINT NOT NULL,

    CONSTRAINT PK_ORDER_ITEM PRIMARY KEY (ID),
    CONSTRAINT FK_ORDER_ITEM_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES HANDCRAFTED_SCHEMA.PRODUCT (ID) ON DELETE CASCADE,
    CONSTRAINT FK_ORDER_ITEM_GIFT_SET_ID FOREIGN KEY (GIFT_SET_ID) REFERENCES HANDCRAFTED_SCHEMA.GIFT_SET (ID) ON DELETE CASCADE,
    CONSTRAINT FK_ORDER_ITEM_ORDER_ID FOREIGN KEY (ORDER_ID) REFERENCES HANDCRAFTED_SCHEMA.ORDER (ID) ON DELETE CASCADE,
    CONSTRAINT CK_CART_ITEM_QUANTITY CHECK ( QUANTITY > 0 ),
    CONSTRAINT CK_ORDER_ITEM_PRODUCT_OR_GIFT_SET CHECK (
        (PRODUCT_ID IS NOT NULL AND GIFT_SET_ID IS NULL) OR
        (PRODUCT_ID IS NULL AND GIFT_SET_ID IS NOT NULL)
        )
    );

CREATE TABLE IF NOT EXISTS HANDCRAFTED_SCHEMA.SHOP_CONTACT
(
    ID BIGINT NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    VALUE VARCHAR(100) NULL,

    CONSTRAINT PK_SHOP_CONTACT PRIMARY KEY (ID)
);

INSERT INTO HANDCRAFTED_SCHEMA.SHOP_CONTACT (ID, NAME)
VALUES
    (1, 'Номер телефону 1'),
    (2, 'Номер телефону 2'),
    (3, 'Telegram'),
    (4, 'Instagram'),
    (5, 'Facebook');
