UPDATE HANDCRAFTED_SCHEMA.SHOP_CONTACT
SET NAME = 'PHONE_NUMBER_1'
WHERE ID = 1;

UPDATE HANDCRAFTED_SCHEMA.SHOP_CONTACT
SET NAME = 'PHONE_NUMBER_2'
WHERE ID = 2;

UPDATE HANDCRAFTED_SCHEMA.SHOP_CONTACT
SET NAME = 'TELEGRAM'
WHERE ID = 3;

UPDATE HANDCRAFTED_SCHEMA.SHOP_CONTACT
SET NAME = 'INSTAGRAM'
WHERE ID = 4;

UPDATE HANDCRAFTED_SCHEMA.SHOP_CONTACT
SET NAME = 'FACEBOOK'
WHERE ID = 5;
